server:
  port: 8081

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**,/category/**
#          filters:
#            - AuthenticationFilter

        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/productInventory/**,/merchant/**,/merchantReport/**
#          filters:
#            - AuthenticationFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/user/**

        - id: CART-ORDER-SERVICE
          uri: lb://CART-ORDER-SERVICE
          predicates:
            - Path=/cart/**,/orderhistory/**
#          filters:
#            - AuthenticationFilter

        - id: EMAIL-SERVICE
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**
#          filters:
#            - AuthenticationFilter


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
